docs: include examples in the docs
DisnakeCommunity/disnake-compass pull request #26
Opened 2023-08-21 08:50 UTC by Snipy7374

Hi, don't merge i still need to emphasize some lines (sigh)

2023-08-21 14:15 UTC, Snipy7374 commented
Now ready to be merged 🙏🏻

2023-08-22 15:03 UTC, Sharp-Eyes requested changes
Thanks for the contribution!

I've added a few points that I think could be improved, but it's looking good overall.

Lastly, I'm thinking we could maybe
- Remove comments from the examples on the github repo,
- Add a link to the docs' examples to the repo in `examples/README.md`,
- Keep the extra explanation only in the docs' examples.

What do you think about this?

2023-08-22 15:03 UTC, Sharp-Eyes commented on docs/source/examples/manager.rst
> +:class:`ComponentManager.as_callback_wrapper` wraps the callbacks of all components registered to that manager along with those of its children. Therefore, if we
These `:class:` directives should be `:meth:` directives. They won't hyperlink until we actually add component managers to the api reference though.

2023-08-22 15:03 UTC, Sharp-Eyes commented on docs/source/examples/select.rst
> +prefix command capabilities, we opt for an :class:`disnake.ext.commands.InteractionBot`.
Could probably make this ``:class:`~disnake.ext.commands.InteractionBot` `` to make it read a little better

2023-08-22 18:09 UTC, Snipy7374 commented
> Thanks for the contribution!
> 
> I've added a few points that I think could be improved, but it's looking good overall.
> 
> Lastly, I'm thinking we could maybe
> - Remove comments from the examples on the github repo,
> - Add a link to the docs' examples to the repo in `examples/README.md`,
> - Keep the extra explanation only in the docs' examples.
> 
> What do you think about this?

Hi, sorry for the late reply.

I'm ok with all the above points, I was already thinking of removing comments when writing all these lines of numbers (it almost seemed like I was crazy giving numbers) also it makes sense that the explanation is on the docs

2023-12-12 23:07 UTC, Sharp-Eyes approved these changes
LGTM! Sorry for the long delay, I finally got back around to working on (and this time around hopefully finishing) the docs.

2023-12-12 23:07 UTC, merged